export interface MbButtonThemeTokens {
  [token: string]: string;
}

export interface MbButtonTokenBundle {
  light: MbButtonThemeTokens;
  dark: MbButtonThemeTokens;
}

export const mbButtonTokens: MbButtonTokenBundle = {
  light: {
    '--mb-btn-focus-ring-brand': '0 0 0 3px rgba(107, 189, 91, 0.18)',
    '--mb-btn-bg-filled-default': '#6bbd5b',
    '--mb-btn-bg-filled-hover': '#5aac4a',
    '--mb-btn-bg-filled-active': '#4d943d',
    '--mb-btn-bg-filled-focus': '#6bbd5b',
    '--mb-btn-bg-filled-disabled': '#d7e8d3',
    '--mb-btn-bg-filled-loading': '#6bbd5b',
    '--mb-btn-text-filled-default': '#103016',
    '--mb-btn-text-filled-hover': '#103016',
    '--mb-btn-text-filled-active': '#103016',
    '--mb-btn-text-filled-focus': '#103016',
    '--mb-btn-text-filled-disabled': '#7c8f77',
    '--mb-btn-text-filled-loading': '#103016',
    '--mb-btn-border-filled-default': '#6bbd5b',
    '--mb-btn-border-filled-hover': '#5aac4a',
    '--mb-btn-border-filled-active': '#4d943d',
    '--mb-btn-border-filled-focus': '#6bbd5b',
    '--mb-btn-border-filled-disabled': '#d7e8d3',
    '--mb-btn-border-filled-loading': '#6bbd5b',
    '--mb-btn-bg-outline-default': '#ffffff',
    '--mb-btn-bg-outline-hover': '#ffffff',
    '--mb-btn-bg-outline-active': '#ffffff',
    '--mb-btn-bg-outline-focus': '#ffffff',
    '--mb-btn-bg-outline-disabled': '#ffffff',
    '--mb-btn-bg-outline-loading': '#ffffff',
    '--mb-btn-text-outline-default': '#6bbd5b',
    '--mb-btn-text-outline-hover': '#5aac4a',
    '--mb-btn-text-outline-active': '#4d943d',
    '--mb-btn-text-outline-focus': '#6bbd5b',
    '--mb-btn-text-outline-disabled': '#8aa08a',
    '--mb-btn-text-outline-loading': '#6bbd5b',
    '--mb-btn-border-outline-default': '#d7e8d3',
    '--mb-btn-border-outline-hover': '#6bbd5b',
    '--mb-btn-border-outline-active': '#4d943d',
    '--mb-btn-border-outline-focus': '#6bbd5b',
    '--mb-btn-border-outline-disabled': '#d8e2d5',
    '--mb-btn-border-outline-loading': '#d7e8d3',
    '--mb-btn-bg-tinted-default': '#eef9e8',
    '--mb-btn-bg-tinted-hover': '#e4f4da',
    '--mb-btn-bg-tinted-active': '#d8efcb',
    '--mb-btn-bg-tinted-focus': '#eef9e8',
    '--mb-btn-bg-tinted-disabled': '#f1f6ee',
    '--mb-btn-bg-tinted-loading': '#eef9e8',
    '--mb-btn-text-tinted-default': '#6bbd5b',
    '--mb-btn-text-tinted-hover': '#5aac4a',
    '--mb-btn-text-tinted-active': '#4d943d',
    '--mb-btn-text-tinted-focus': '#6bbd5b',
    '--mb-btn-text-tinted-disabled': '#8aa08a',
    '--mb-btn-text-tinted-loading': '#6bbd5b',
    '--mb-btn-bg-plain-default': 'transparent',
    '--mb-btn-bg-plain-hover': 'transparent',
    '--mb-btn-bg-plain-active': 'transparent',
    '--mb-btn-bg-plain-focus': 'transparent',
    '--mb-btn-bg-plain-disabled': 'transparent',
    '--mb-btn-bg-plain-loading': 'transparent',
    '--mb-btn-text-plain-default': '#6bbd5b',
    '--mb-btn-text-plain-hover': '#5aac4a',
    '--mb-btn-text-plain-active': '#4d943d',
    '--mb-btn-text-plain-focus': '#6bbd5b',
    '--mb-btn-text-plain-disabled': '#8aa08a',
    '--mb-btn-text-plain-loading': '#6bbd5b'
  },
  dark: {
    '--mb-btn-focus-ring-brand': '0 0 0 3px rgba(140, 203, 120, 0.22)',
    '--mb-btn-bg-filled-default': '#8ccb78',
    '--mb-btn-bg-filled-hover': '#9ad485',
    '--mb-btn-bg-filled-active': '#73b861',
    '--mb-btn-bg-filled-focus': '#8ccb78',
    '--mb-btn-bg-filled-disabled': '#41573f',
    '--mb-btn-bg-filled-loading': '#8ccb78',
    '--mb-btn-text-filled-default': '#10210f',
    '--mb-btn-text-filled-hover': '#10210f',
    '--mb-btn-text-filled-active': '#10210f',
    '--mb-btn-text-filled-focus': '#10210f',
    '--mb-btn-text-filled-disabled': '#d2d9cf',
    '--mb-btn-text-filled-loading': '#10210f',
    '--mb-btn-border-filled-default': '#8ccb78',
    '--mb-btn-border-filled-hover': '#9ad485',
    '--mb-btn-border-filled-active': '#73b861',
    '--mb-btn-border-filled-focus': '#8ccb78',
    '--mb-btn-border-filled-disabled': '#41573f',
    '--mb-btn-border-filled-loading': '#8ccb78',
    '--mb-btn-bg-outline-default': '#1b251a',
    '--mb-btn-bg-outline-hover': '#253727',
    '--mb-btn-bg-outline-active': '#152117',
    '--mb-btn-bg-outline-focus': '#1b251a',
    '--mb-btn-bg-outline-disabled': '#1b251a',
    '--mb-btn-bg-outline-loading': '#1b251a',
    '--mb-btn-text-outline-default': '#b5c7b3',
    '--mb-btn-text-outline-hover': '#d7f0d0',
    '--mb-btn-text-outline-active': '#c0e3b7',
    '--mb-btn-text-outline-focus': '#b5c7b3',
    '--mb-btn-text-outline-disabled': '#7f8b7c',
    '--mb-btn-text-outline-loading': '#b5c7b3',
    '--mb-btn-border-outline-default': '#4a5947',
    '--mb-btn-border-outline-hover': '#6d8d68',
    '--mb-btn-border-outline-active': '#5c7c58',
    '--mb-btn-border-outline-focus': '#4a5947',
    '--mb-btn-border-outline-disabled': '#4a5947',
    '--mb-btn-border-outline-loading': '#4a5947',
    '--mb-btn-bg-tinted-default': '#1c2a1e',
    '--mb-btn-bg-tinted-hover': '#253727',
    '--mb-btn-bg-tinted-active': '#152117',
    '--mb-btn-bg-tinted-focus': '#1c2a1e',
    '--mb-btn-bg-tinted-disabled': '#1b251a',
    '--mb-btn-bg-tinted-loading': '#1c2a1e',
    '--mb-btn-text-tinted-default': '#b5c7b3',
    '--mb-btn-text-tinted-hover': '#d7f0d0',
    '--mb-btn-text-tinted-active': '#c0e3b7',
    '--mb-btn-text-tinted-focus': '#b5c7b3',
    '--mb-btn-text-tinted-disabled': '#7f8b7c',
    '--mb-btn-text-tinted-loading': '#b5c7b3',
    '--mb-btn-bg-plain-default': 'transparent',
    '--mb-btn-bg-plain-hover': 'transparent',
    '--mb-btn-bg-plain-active': 'transparent',
    '--mb-btn-bg-plain-focus': 'transparent',
    '--mb-btn-bg-plain-disabled': 'transparent',
    '--mb-btn-bg-plain-loading': 'transparent',
    '--mb-btn-text-plain-default': '#b5c7b3',
    '--mb-btn-text-plain-hover': '#d7f0d0',
    '--mb-btn-text-plain-active': '#c0e3b7',
    '--mb-btn-text-plain-focus': '#b5c7b3',
    '--mb-btn-text-plain-disabled': '#7f8b7c',
    '--mb-btn-text-plain-loading': '#b5c7b3'
  }
};
